# Generated by Django 3.0.5 on 2020-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='parquiztime',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='parwklyquiz',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='parwkndquiz',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
