# Generated by Django 3.0.5 on 2020-08-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200803_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='progress',
        ),
    ]
