# Generated by Django 3.0.5 on 2020-08-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_eligible_ongoingcontests_upcomingcontests_winners'),
    ]

    operations = [
        migrations.CreateModel(
            name='contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestname', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('upcoming', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='ongoingcontests',
        ),
        migrations.DeleteModel(
            name='upcomingcontests',
        ),
    ]
