# Generated by Django 3.0.5 on 2020-08-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiztime', models.IntegerField()),
                ('parquiztime', models.BooleanField()),
                ('weekendquiz', models.IntegerField()),
                ('parwkndquiz', models.BooleanField()),
                ('weeklyquiz', models.IntegerField()),
                ('parwklyquiz', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
