# Generated by Django 3.0.5 on 2020-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(default='profilepics/profilepic.jpeg', upload_to='Profilepics'),
        ),
    ]
