# Generated by Django 3.0.5 on 2020-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200804_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='eligible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz',
            field=models.IntegerField(default=0),
        ),
    ]
