# Generated by Django 3.0.5 on 2020-08-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200805_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eligible',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rewards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
