# Generated by Django 3.0.5 on 2020-08-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200813_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='male', max_length=8, null=True),
        ),
    ]
