from django.db import models
# Create your models here.

class Video(models.Model):
    video_id=models.CharField(max_length=20)
    title = models.CharField(max_length=150)
    embedlink = models.CharField(max_length=200)
    youtubelink = models.CharField(max_length=200)
    date = models.CharField(max_length=20)

class Article(models.Model):
    article_id=models.CharField(max_length=20)
    title= models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    content=models.TextField()
    date=models.CharField(max_length=20)
    author=models.CharField(max_length=50)
    image=models.ImageField(upload_to="pics") 

class Weeksuggestions(models.Model):
    title=models.CharField(max_length=150)
    link=models.CharField(max_length=200)
    date=models.CharField(max_length=20)
    image=models.ImageField(upload_to="pics")

class Movie(models.Model):
    title=models.CharField(max_length=25)
    OTT_link=models.CharField(max_length=100)
    trailer=models.CharField(max_length=150)
    image=models.ImageField(upload_to="pics")
    year=models.IntegerField()
    plot=models.TextField()
    genre=models.CharField(max_length=100)
    rating=models.IntegerField()
    length=models.IntegerField()
    actors=models.CharField(max_length=200)
    producer=models.CharField(max_length=50)
    director=models.CharField(max_length=50)
    language=models.CharField(max_length=20,default="english")
    upcoming=models.BooleanField(default="False")
    OTT_date=models.CharField(max_length=30)
    OTT_name=models.CharField(max_length=30)
    trending=models.BooleanField(default="False")
    suggested=models.BooleanField(default="False")
    action=models.BooleanField()
    adv=models.BooleanField()
    comedy=models.BooleanField()
    drama=models.BooleanField()
    fantasy=models.BooleanField()
    horror=models.BooleanField()
    scifi=models.BooleanField()
    thriller=models.BooleanField()
    romance=models.BooleanField()
    latestnetflixmovie=models.BooleanField(default="False")
    upcomingnetflixmovie=models.BooleanField(default="False")
    latestprimemovie=models.BooleanField(default="False")
    upcomingprimemovie=models.BooleanField(default="False")
    toprated=models.BooleanField(default="False")
    top=models.BooleanField(default="False")



class Series(models.Model):
    title=models.CharField(max_length=25)
    OTT_link=models.CharField(max_length=100)
    trailer=models.CharField(max_length=150)
    image=models.ImageField(upload_to="pics")
    season=models.IntegerField()
    year=models.IntegerField()
    plot=models.TextField()
    genre=models.CharField(max_length=20)
    rating=models.IntegerField()
    actors=models.CharField(max_length=200)
    producer=models.CharField(max_length=100)
    director=models.CharField(max_length=100)
    language=models.CharField(max_length=20,default="english")
    upcoming=models.BooleanField(default="False")
    suggested=models.BooleanField(default="False")
    OTT_date=models.CharField(max_length=30)
    OTT_name=models.CharField(max_length=30)
    trending= models.BooleanField(default="False")
    action=models.BooleanField()
    adv=models.BooleanField()
    comedy=models.BooleanField()
    drama=models.BooleanField()
    fantasy=models.BooleanField()
    horror=models.BooleanField()
    scifi=models.BooleanField()
    thriller=models.BooleanField()
    romance=models.BooleanField()
    latestnetflixseries=models.BooleanField(default="False")
    upcomingnetflixseries=models.BooleanField(default="False")
    latestprimeseries=models.BooleanField(default="False")
    upcomingprimeseries=models.BooleanField(default="False")
    toprated=models.BooleanField(default="False")
    top=models.BooleanField(default="False")
    mwprime=models.BooleanField(default="False")
    mwnetflix=models.BooleanField(default="False")
    mwhotstar=models.BooleanField(default="False")

class Animes(models.Model):
    title=models.CharField(max_length=25)
    OTT_link=models.CharField(max_length=100)
    trailer=models.CharField(max_length=150)
    image=models.ImageField(upload_to="pics")
    season=models.IntegerField()
    year=models.IntegerField()
    plot=models.TextField()
    genre=models.CharField(max_length=20)
    rating=models.IntegerField()
    actors=models.CharField(max_length=100)
    producer=models.CharField(max_length=100)
    director=models.CharField(max_length=100)
    upcoming=models.BooleanField(default="False")
    OTT_date=models.CharField(max_length=30)
    Toprated=models.BooleanField(default="False")
    Top10=models.BooleanField(default="False")

class Mainslide(models.Model):
    image=models.ImageField(upload_to="slides")
    contest=models.CharField(max_length=30)



class latestnews(models.Model):
    title=models.CharField(max_length=20)
    link=models.CharField(max_length=50)
    image=models.ImageField(upload_to="news")
    date=models.CharField(max_length=15)