# Generated by Django 3.0.5 on 2020-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('OTT_link', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pics')),
                ('season', models.IntegerField()),
                ('year', models.IntegerField()),
                ('plot', models.TextField()),
                ('genre', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('actors', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('upcoming', models.BooleanField(default='False')),
                ('OTT_date', models.CharField(max_length=30)),
                ('Toprated', models.BooleanField(default='False')),
                ('Top10', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='latestnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='news')),
                ('date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mainslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides')),
                ('contest', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('OTT_link', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pics')),
                ('season', models.IntegerField()),
                ('year', models.IntegerField()),
                ('plot', models.TextField()),
                ('genre', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('actors', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('language', models.CharField(default='english', max_length=20)),
                ('upcoming', models.BooleanField(default='False')),
                ('suggested', models.BooleanField(default='False')),
                ('OTT_date', models.CharField(max_length=30)),
                ('OTT_name', models.CharField(max_length=30)),
                ('trending', models.BooleanField(default='False')),
                ('latestnetflixseries', models.BooleanField(default='False')),
                ('upcomingnetflixseries', models.BooleanField(default='False')),
                ('latestprimeseries', models.BooleanField(default='False')),
                ('upcomingprimeseries', models.BooleanField(default='False')),
                ('toprated', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('embedlink', models.CharField(max_length=200)),
                ('youtubelink', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weeksuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
