# Generated by Django 3.0.5 on 2020-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('OTT_link', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pics')),
                ('year', models.IntegerField()),
                ('plot', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('length', models.IntegerField()),
                ('actors', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('language', models.CharField(default='english', max_length=20)),
                ('upcoming', models.BooleanField(default='False')),
                ('OTT_date', models.CharField(max_length=30)),
                ('OTT_name', models.CharField(max_length=30)),
                ('trending', models.BooleanField(default='False')),
                ('suggested', models.BooleanField(default='False')),
                ('action', models.BooleanField()),
                ('adv', models.BooleanField()),
                ('comedy', models.BooleanField()),
                ('drama', models.BooleanField()),
                ('fantasy', models.BooleanField()),
                ('horror', models.BooleanField()),
                ('scifi', models.BooleanField()),
                ('thriller', models.BooleanField()),
                ('romance', models.BooleanField()),
                ('latestnetflixmovie', models.BooleanField(default='False')),
                ('upcomingnetflixmovie', models.BooleanField(default='False')),
                ('latestprimemovie', models.BooleanField(default='False')),
                ('upcomingprimemovie', models.BooleanField(default='False')),
                ('Toprated', models.BooleanField(default='False')),
                ('Top', models.BooleanField(default='False')),
            ],
        ),
    ]
