# Generated by Django 3.0.5 on 2020-08-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20200820_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anime',
            new_name='Animes',
        ),
        migrations.AddField(
            model_name='series',
            name='mwhotstar',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='series',
            name='mwnetflix',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='series',
            name='mwprime',
            field=models.BooleanField(default='False'),
        ),
    ]
